export const LoginUser="LoginUser"
export const LogoutUser="LogoutUser"
export const AllProjects="AllProjects"
export const SetAccesToken="Set_accesToken"
export const SECRET_KEY="QWERTYUIOP7894561234567890"
export const SETUSERNAME="SETUSERNAME"
export const SetUsername="Set_Username"
export const SetMessages="Set_Messages"
export const SetNotifications="Set_Notification"
export const SetContacts="Set_Contacts"
export const SetProjects="SETSAVEDPROJECT"
export const SetFollowings="SETFOLLOWING"
export const SetFollow="SETFOLLOWERS"
export const UpdateLikeList="UPDATINGLIKEDLIST"

